### ISSUE TITLE
Inexplicable crashes trying to boot the Big Sur installer

### ISSUE THREAD

**Issue by halian** [LucasDondo/Hackintosh-Lenovo-IdeaPad-330-15IKB-81DE#2]
Per topic. A representative crash log is attached. I first chased this up with the /r/hackintosh Discord only for the owner themself to be baffled by the crashes, since nothing we could think of seemed to help.
[panic-2021-08-01-193143.txt](https://github.com/LucasDondo/Hackintosh-Lenovo-IdeaPad-330-15IKB-81DE/files/6918900/panic-2021-08-01-193143.txt)

**Comment by halian** [comment]
Rarely it does boot, but then hangs after sitting on "Examining volumes…" for about a minute.

**Comment by LucasDondo** [comment]
Hello @halian! I'll take a look at the log you sent, but I no longer use macOS, therefore I won't be able to test nothing whatsoever, I'm sad to announce. Yes, I should (and will) announce that in the [README.md](https://github.com/LucasDondo/Hackintosh-Lenovo-IdeaPad-330-15IKB-81DE/blob/master/README.md) file.
As I come to understand, your boot arguments (and kexts?) are different from mine, but I suppose you already used the ones I used without modification, so no comment here.
However, I must note that I never tried to install macOS Big Sur with this (nor any other) EFI.

**Comment by halian** [comment]
I'm guessing you tried Catalina last?

**Comment by LucasDondo** [comment]
That's right. And that worked perfectly fine for me.

**Comment by halian** [comment]
I'm out of town right now but will make sure to try Catalina when I return.

**Comment by halian** [comment]
Continued in #4.
