### ISSUE TITLE
NVMe crash trying to boot the Catalina installer

### ISSUE THREAD

**Issue by halian** [LucasDondo/Hackintosh-Lenovo-IdeaPad-330-15IKB-81DE#4]
Since in #2 Lucas said that he last successfully booted Catalina, I decided to give that a try. Unfortunately it, too, crashes, namely in the NVMe driver.

[Here's](https://cdn.discordapp.com/attachments/349988041797926913/874745547167248444/image0.jpg) an image of the crash dump, since no dump file was left behind.

**Comment by halian** [comment]
Asking around in the [r/Hackintosh's Discord server](https://discord.com/invite/Wxam8aH), apparently it's an iGPU issue, which utterly baffles me. The suggested fix was to add NVMe kexts; will try that and report back.

**Comment by halian** [comment]
Unfortunately, adding NVMe kexts changed nothing; it still crashes in the same way for the same apparent reason.

**Comment by halian** [comment]
It was the Optane stick. With that removed, it boots, but there's no Wi-Fi.

**Comment by halian** [comment]
Ordered a compatible replacement Wi-Fi chip; Catalina installer runs flawlessly, but the installed O/S crashes on boot. I am now chasing down the cause of that crash.

**Comment by LucasDondo** [comment]
How did it go with the new Wi-Fi chip?

**Comment by halian** [comment]
I never could figure out what caused the crashes on boot, and so put Windows back on the laptop a while ago. :/
